#!/bin/sh

start_ifplugd() {

}

start () {

}

stop () {

}

plugged () {

}

case $1 in
	start|boot)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 2
		start
		;;
	disable)
		;;
	plugged)
		plugged $2
		;;
	*)
		echo "Syntax: $0 [command]"
		echo ""
		echo "Available commands:"
		echo "	start   Start the service"
		echo "	stop    Stop the service"
		echo "	restart Restart the service"
		echo "	disable Disable the service"
		echo "	plugged check if iface is plugged"
		;;
esac


