log4cplus.rootLogger=TRACE, ALL_MSGS

log4cplus.appender.ALL_MSGS=log4cplus::RollingFileAppender
log4cplus.appender.ALL_MSGS.MaxFileSize=204800
log4cplus.appender.ALL_MSGS.MaxBackupIndex=5
log4cplus.appender.ALL_MSGS.File=/var/log/l3vpn.log
log4cplus.appender.ALL_MSGS.layout=log4cplus::PatternLayout
log4cplus.appender.ALL_MSGS.layout.ConversionPattern=%d{%m/%d/%y %H:%M:%S} %-5p - %m%n
log4cplus.appender.ALL_MSGS.filters.1=log4cplus::spi::LogLevelRangeFilter
log4cplus.appender.ALL_MSGS.filters.1.LogLevelMin=DEBUG
log4cplus.appender.ALL_MSGS.filters.1.LogLevelMax=ERROR
log4cplus.appender.ALL_MSGS.filters.1.AcceptOnMatch=true
log4cplus.appender.append_1.filters.2=log4cplus::spi::DenyAllFilter
