#!/bin/sh

# lilu
#interval > 3min

intel_modem_ifce=wwan1
ping_addr='www.e-chong.com'
ping_testip='8.8.8.8'

tmpdir="/var/g3modem"
if [ ! -e $tmpdir ] ; then
	mkdir -p $tmpdir &> /dev/null
fi

if [ -e $tmpdir/g3monitor.pid ] ; then
	echo "$$" >> $tmpdir/g3monitor.pid
	cnt=$(awk 'END{print FNR}' $tmpdir/g3monitor.pid)
	if [ $cnt -ge 10 ] ; then
		logger -t 3gmonitor -p error "g3monitor can not normal exit"
		sh /usr/sbin/savelog
		reboot
	fi
	echo "g3monitor is running PID: "
	echo "$(cat $tmpdir/g3monitor.pid)"
	exit 0
	#kill $(cat $tmpdir/g3monitor.pid) &> /dev/null
	#rm $tmpdir/g3monitor.pid &> /dev/null
fi

echo "$$" > $tmpdir/g3monitor.pid


lose_cnt=$(awk 'FNR==1{print $0}' $tmpdir/g3monitor_data)
run_cnt=$(awk 'FNR==2{print $0}' $tmpdir/g3monitor_data)
if [ -z "$lose_cnt" ]; then
	lose_cnt=0
fi
if [ -z "$run_cnt" ]; then
	run_cnt=0
fi

reset_modem()
{ #$1 interface
	ubus -S list "network.interface.$1" > /dev/null || {
		echo "Interface $1 not found"
		return 2
	}
	section=network.$1
	if [ "$(uci get $section)" = "interface" ] && [ "$(uci get $section.proto)" = "3g" ]; then
		dev=$(uci get $section.device 2> /dev/null)
		atdev=$(uci get $section.atdevice 2> /dev/null)
		if [ -n "$dev" ] && [ -n "$atdev" ] && [ -e $dev ] && [ -e $atdev ] ; then
			#restart
		        ifdown $1 &> /dev/null
		        sleep 6
		        #hardware reset
			sh /usr/sbin/g3command $dev -AT '+++' &> /dev/null
			sleep 2
			sh /usr/sbin/g3command $dev -AT 'AT\^RESET' -show &> $tmpdir/tmpdata
			[ -z "$(cat $tmpdir/tmpdata | egrep -o 'OK')" ] && [ ! -e $tmpdir/g3info${atdev##*/}.pid ] && {	
				sh /usr/sbin/g3command $atdev -AT 'AT\^RESET' -show &> $tmpdir/tmpdata
				#wwan1
				if [ "$intel_modem_ifce" = "$1" ] ; then
				if [ -z "$(cat $tmpdir/tmpdata)" ] || \
				[ -n "$(cat $tmpdir/tmpdata | egrep -o 'Could not write to COM device')" ] ; then
					logger -t 3gmonitor -p error "Internal modem can not work normally(RESET)"
					sh /usr/sbin/savelog
					reboot
				fi
				fi
			}

		        logger -t 3gmonitor -p notice "Reset 3G modem($1)"
		        sleep 22
		        #ifup $infce &> /dev/null
			sh /usr/sbin/g3modem -ifce $1
			
		else
			echo "Interface $1 Error: device ${dev:-unknown} and atdevice ${atdev:-unknown}"
		fi
	else
		echo "Interface $1 isn't 3g protocol"
	fi
}


if [ -n "$1" ] ; then
	case $1 in
	-reset)
		if [ -n "$2" ] ; then
			reset_modem $2
		else
			echo "script -reset <(3g)interface>"
		fi
	;;
	*)
		echo "script -reset <(3g)interface>"
	;;
	esac
else

	#logger -t 3gmonitor -p notice "3G interface monitor is doing"
	if [ $run_cnt -lt 20000 ]; then
		let run_cnt++	
	fi
	#ping=$(ping -c 4 -W 3 -s 4 -q www.e-chong.com)
	pi=$(ping -c 4 -W 5 -s 4 -q $ping_addr | egrep -o '[0-9]{1,3}% packet loss')
	if [ -n "$pi" ]; then
		if [ ${pi%%\%*} -eq 100 ]; then
			#100% packet loss
			#let lose_cnt++
			logger -t 3gmonitor -p warn "100% packet loss"
		else
			lose_cnt=0
		fi
		  
		#HUAWEI LTE 
		section=network.$intel_modem_ifce
		dev=$(uci get $section.device 2> /dev/null)
		atdev=$(uci get $section.atdevice 2> /dev/null)
		[ -n "$atdev" ] && [ -e $atdev ] && {
			tmp=$(sh /usr/sbin/g3command $atdev -AT 'AT\^SYSCFGEX?' -show)
			[ -n "$(echo $tmp | egrep -o 'OK')" ] && \ 
			[ -z "$(echo $tmp | egrep -o '\"00\",3FFFFFFF,1,2,7FFFFFFFFFFFFFFF')" ] && {
				logger -t 3gmonitor -p notice "Try to initialize the internal Modem($intel_modem_ifce)" 
				sh /usr/sbin/g3modem -hwinit
			}
		}
	    
	else
		#ping: unknown host www.e-chong.com
		if [ $lose_cnt -lt 100 ]; then
			let lose_cnt++
		else
			logger -t 3gmonitor -p error "Internal modem can not work normally"
			sh /usr/sbin/savelog
			reboot	
		fi
	
		logger -t 3gmonitor -p error "(lose $lose_cnt run $run_cnt) unknown host"

		section=network.$intel_modem_ifce
		dev=$(uci get $section.device 2> /dev/null)
		atdev=$(uci get $section.atdevice 2> /dev/null)
		if [ -n "$dev" ] && [ -n "$atdev" ] && [ -e $dev ] && [ -e $atdev ] ; then
       		if [ "$(uci get $section)" = "interface" ] && [ "$(uci get $section.proto)" = "3g" ]; then 
			#if [ -n "$(ping -I 3g-$intel_modem_ifce -c 4 -W 3 -s 4 -q $ping_addr | \
			#egrep -o '[0-9]{1,3}% packet loss')" ]; then			
			if [ -n "$(ping -I 3g-$intel_modem_ifce -c 4 -W 3 -s 4 -q $ping_addr | egrep -o '[0-9]{1,3}% packet loss')" ]; then
				lose_cnt=0
				#if [ -n "$(ip route list table 0 | egrep -o 'table [0-9]{1,3}')" ]; then
					#logger -t 3gmonitor -p notice "(no route list table)set mwan3"
				#	env -i ACTION=ifup INTERFACE=wwan1 DEVICE=3g-wwan1 /sbin/hotplug-call iface
				#fi
			else
				if [ $run_cnt -ge 2 ]; then
					reset_modem $intel_modem_ifce
					run_cnt=0		
				fi
			fi		
		fi
		fi

	#	ifces=$(ubus list network.interface.* | awk -F. '{print $3}')
	#	[ -n "$ifces" ] && for ifce in $ifces; do
	#		if [ "$(uci get network.$ifce.proto)" = "3g" ]; then
	#		fi
	#	done

	
	#	infce=$(ifconfig | grep '3g')
	#	if [ ${#infce} -gt 0 ]; then
	#		for word in $infce; do
	#			if [ ${word%%-*} = '3g' ]; then
	#				if [ "$(ip route | grep default.*$word)" = "" ]; then
	#					# no default gw
	#					a2=$(ifconfig $word | egrep -o "P-t-P:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}")
	#					a3=${a2:6}
	#					route add default gw $a3 metric 3
	#					logger -t 3gmonitor -p notice "Interface $word add default gw"
	#					env -i ACTION=ifup INTERFACE=${word:3} DEVICE=$word /sbin/hotplug-call iface
	#				fi
	#			fi
	#		done
	#	fi
	
	
	fi

echo "$lose_cnt" > $tmpdir/g3monitor_data
echo "$run_cnt" >> $tmpdir/g3monitor_data
 
fi #[ -n "$1" ]

 
#kill $(cat $tmpdir/g3monitor.pid) &> /dev/null
rm $tmpdir/g3monitor.pid &> /dev/null
exit 0

