#!/bin/sh

tmpdir="/var/g3modem"
if [ ! -e $tmpdir ] ; then
	mkdir -p $tmpdir &> /dev/null
fi

intel_modem_ifce=wwan1

hw_intel_init()
{
	section=network.$1
	dev=$(uci get $section.device 2> /dev/null)
	atdev=$(uci get $section.atdevice 2> /dev/null)
	if [ -n "$dev" ] && [ -n "$atdev" ] && [ -e $dev ] && [ -e $atdev ] ; then
	#tmp=$(sh /usr/sbin/g3command $dev -AT 'AT\^SYSCFGEX=\"00\",3FFFFFFF,1,2,7FFFFFFFFFFFFFFF,,' -show | egrep -o 'OK')
	#[ -z "$tmp" ] && {
		trycnt=8
		rm -f $tmpdir/tmpdata 2> /dev/null
		tmp=$(sh /usr/sbin/g3command $atdev -AT 'AT\^SYSCFGEX=\"00\",3FFFFFFF,1,2,7FFFFFFFFFFFFFFF,,' -show | egrep -o 'OK')
		while [ -z "$tmp" ] && [ $trycnt -gt 0 ] ;
		do {
		let trycnt--
		sleep 1
		tmp=$(sh /usr/sbin/g3command $atdev -AT 'AT\^SYSCFGEX=\"00\",3FFFFFFF,1,2,7FFFFFFFFFFFFFFF,,' -show | egrep -o 'OK')
		}
		done
		if [ -z "$tmp" ] ; then 
			logger -t g3modem -p warn "Internal Modem($intel_modem_ifce) initialization failed" 
		else
			logger -t g3modem -p notice "Internal Modem($intel_modem_ifce) initialization successfully" 
		fi
	#}
#	return $tmp
#	else
#	return 'Error'	
	fi
}

g3modem_intel_init()
{  #$1 interface
	#HUAWEI LET initialize  $intel_modem_ifce
	section=network.$1
	dev=$(uci get $section.device 2> /dev/null)
	atdev=$(uci get $section.atdevice 2> /dev/null)
	if [ -n "$dev" ] && [ -n "$atdev" ] && [ -e $dev ] && [ -e $atdev ] ; then
		#tmp=$(sh /usr/sbin/g3command $dev -AT 'AT\^LEDCTRL=1' -show | egrep -o 'OK')
		#[ -z "$tmp" ] && {
			sh /usr/sbin/g3command $atdev -AT 'AT\^LEDCTRL=1'
		#}
	fi
}


set_if_up() 
{  #$1 interface
	section=network.$1
	dev=$(uci get $section.device 2> /dev/null)
	atdev=$(uci get $section.atdevice 2> /dev/null)
	if [ -n "$dev" ] && [ -n "$atdev" ] && [ -e $dev ] && [ -e $atdev ] ; then
        if [ "$(uci get $section)" = "interface" ] && [ "$(uci get $section.proto)" = "3g" ]; then 
		#ifdown $1
		#sleep 8
		
		rm $tmpdir/tmpdata &> /dev/null
		sh /usr/sbin/g3command $dev -operator -show &> $tmpdir/tmpdata
		operator=$(cat $tmpdir/tmpdata | grep "COPS:" | awk -F, '{print $3}')
		[ -z "$operator" ] && {
			sh /usr/sbin/g3command $atdev -operator -show &> $tmpdir/tmpdata
                	operator=$(cat $tmpdir/tmpdata | grep "COPS:" | awk -F, '{print $3}')
		}
		[ -z "$operator" ] && {
			operator=$(awk -F: '/COPS:.*/{print $2}' $tmpdir/g3info${atdev##*/} | awk -F, 'END{print $3}')
		}
		if [ -n "$operator" ]; then
			if [ "$operator" = "\"CHN-UNICOM\"" ] || [ "$operator" = "\"UNICOM\"" ] || [ "$operator" = "\"46001\"" ]; then
			#china unicom
			uci set $section.apn=3gnet
			uci set $section.dialnumber=*99#
			uci commit network
			elif [ "$operator" = "\"CHINA MOBILE\"" ] || [ "$operator" = "\"CMCC\"" ] || [ "$operator" = "\"46000\"" ]; then
			#china mobile
			uci set $section.apn=cmnet
			uci set $section.dialnumber=*99***1#
			uci commit network
			else
			logger -t g3modem -p warn "Interface $1 unknown SIM operator" 
			fi
			[ -n "$(ifconfig 3g-$1 | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" ] || {
				#[ "$1" = "$intel_modem_ifce" ] && hw_intel_init $1
				sleep 1
				ifup $1				
			}
		else
			rm $tmpdir/tmpdata &> /dev/null
			#sh /usr/sbin/read3ginfo $dev -sim -show &> $tmpdir/tmpdata
			sh /usr/sbin/g3command $dev -sim -show &> $tmpdir/tmpdata
			sim=$(cat $tmpdir/tmpdata | egrep -o "[0-9]{15}")
			[ -z "$sim" ] && { 
				#sh /usr/sbin/read3ginfo $atdev -sim -show &> $tmpdir/tmpdata
				sh /usr/sbin/g3command $atdev -sim -show &> $tmpdir/tmpdata
				sim=$(cat $tmpdir/tmpdata | egrep -o "[0-9]{15}")
			}
			[ -z "$sim" ] && { 
				sim=$(awk -F: '/SIMID:.*/{print $2}' $tmpdir/g3info${atdev##*/} | egrep -o "[0-9]{15}")
			}
			if [ -n "$sim" ] ; then
			[ -n "$(ifconfig 3g-$1 | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" ] || {
				#[ "$1" = "$intel_modem_ifce" ] && hw_intel_init $1
				sleep 1
				ifup $1
			}
			else
				ifdown $1
				#echo "Interface $1 no SIM card" 
				logger -t g3modem -p warn "Interface $1 no SIM card" 
			fi
			#echo "Interface $1 can not get operator" 
			logger -t g3modem -p warn "Interface $1 can't get SIM operator" 
		fi #device
        fi 
	fi

} 

if [ -n "$1" ]; then
	case $1 in
	-intel)
		#modem initialize
		set_if_up $intel_modem_ifce
		hw_intel_init $intel_modem_ifce
		g3modem_intel_init $intel_modem_ifce
		#logger -t g3modem -p notice "Interface $intel_modem_ifce Internal Modem initialized" 
	;;
	-hwinit)
		hw_intel_init $intel_modem_ifce
	;;
	-ifce) 
		ubus -S list "network.interface.$2" > /dev/null || {
			echo "Interface $2 not found"
			return 2
		}
		set_if_up $2
		#wwan1
		if [ "$intel_modem_ifce" = "$2" ] ; then		
			hw_intel_init $intel_modem_ifce
		fi
	;;
	-help)
		echo 'script -intel(default interface)'
		echo 'script -ifce Interface'
		echo 'script -hwinit(HW LET)'
		echo 'script -help'
	;;
	esac
fi

