#!/bin/sh

pingip='10.9.8.2'   # ping DB server
pingip2='124.202.140.34'

route add -net 10.9.8.0 gateway 10.9.8.100 netmask 255.255.248.0 dev ppp0
route add -net 10.9.8.0 gateway 10.9.8.100 netmask 255.255.248.0 dev ppp1
route add -net 10.9.8.0 gateway 10.9.8.100 netmask 255.255.248.0 dev ppp2

if ping -q -c 2 "$pingip" >> /dev/null ; then      # ping is good - bring iface up
        if [ $? -eq 0 ] ; then
            echo "vpn is up"
        fi
    else                                # ping is bad, iface is down
        if [ $? -eq 1 ] ;  then
            echo "vpn is down"
            /bin/sh /root/setup_vpn.sh
        fi
    fi

if ping -q -c 2 "$pingip2" >> /dev/null ; then      # ping is good - bring iface up
        if [ $? -eq 0 ] ; then
            echo "network is up"
        fi
    else                                 # ping is bad, iface is down
        if [ $? -eq 1 ] ;  then
            echo "network is down"
            echo "`date`: network is down" >> /mnt/umemory/routerlog/network.log 
        fi
    fi

