#!/bin/sh

pingip='10.168.1.1'   # ping Gateway swith to DB server later
pingip2='114.119.6.180'  # Mobile 

        route add -net 10.168.0.0 gateway 10.168.1.1 netmask 255.255.0.0 dev ppp1
	route add -net 10.168.0.0 gateway 10.168.1.1 netmask 255.255.0.0 dev ppp2
	route add -net 10.168.0.0 gateway 10.168.1.1 netmask 255.255.0.0 dev ppp3

if ping -q -c 2 "$pingip" >> /dev/null ; then      # ping is good - bring iface up
        if [ $? -eq 0 ] ; then
            echo "vpn is up"
        fi
    else                                # ping is bad, iface is down
        if [ $? -eq 1 ] ;  then
            echo "9qu vpn is down"
            /bin/sh /root/setup_9qu.sh >/tmp/vpn.log 2>&1
        fi
    fi

if ping -q -c 2 "$pingip2" >> /dev/null ; then      # ping is good - bring iface up
        if [ $? -eq 0 ] ; then
            echo "network is up"
        fi
    else                                 # ping is bad, iface is down
        if [ $? -eq 1 ] ;  then
            echo "network is down"
            echo "`date`: 9qu network is down" >> /mnt/umemory/routerlog/network.log 
        fi
    fi

