#!/bin/sh /etc/rc.common

# /init.d/evserver

START=99

start()
{
	{
	while true
	do
		ping www.e-chong.com -w 1 -c 5 | grep -q "ttl=" && break || continue
	done
	}&
	/bin/EV_server &
}

stop()
{
		killall -9 EV_server
}

